### ISSUE TITLE
Sensors become Unavailable after 15 minutes

### ISSUE THREAD

**Issue by mihsu81** [chkuendig/hass-amphiro-ble#10]
Hi @chkuendig,

The sensors become Unavailable after 15 minutes of not receiving data from the shower head. HA shows a notification that the integration amphiro_ble doesn't provide these entities anymore.
Is this expected behaviour? Is there any way to have the sensors keep their values?
Thanks in advance.

![image](https://github.com/chkuendig/hass-amphiro-ble/assets/40715497/6b6a9262-e35c-4141-9829-46df72b8fec7)

**Comment by chkuendig** [comment]
I think thats the regular behaviour for sensors that arent continuously active. This also happens for other devices if I unplug them. (the showerhead loses power if its not running)

**Comment by mihsu81** [comment]
I have seen other integrations have implemented ways to restore the state of the sensor after a restart.
Like https://github.com/custom-components/ble_monitor

![image](https://github.com/chkuendig/hass-amphiro-ble/assets/40715497/0508724d-271f-4a9c-af00-2e9cfd94182a)

If you think it is too difficult to add in this integration, do you have any examples of your approach in your instance of HA to get around this limitation?

Thanks.

**Comment by mihsu81** [comment]
Also, the sensors of the native Xiaomi BLE integration keep their last state after a restart.
So I guess something must be missing from the integration that adds this functionality.

**Comment by gilcu3** [comment]
@chkuendig thank you for this integration. I have recently began using it and it works like a charm.

Regarding the topic of this issue, I have to agree with @mihsu81, I think the expected behavior for bluetooth sensors that are not always connected is to retain the last value available. One official integration that comes to my mind that has this behavior is [oral-b](https://www.home-assistant.io/integrations/oralb). It tracks quite similar sensors (time, and others) while the tooth brush is working, then keeps them until the next time they are used, even if there are reboots. 

Would you consider again adding this feature, or at least accepting PRs adding it? I would be happy to do the later if you are willing to accept it.

**Comment by chkuendig** [comment]
Happy to merge a PR, I so far just didnt have time to look into this myself.
